### PR TITLE
FileDialog API was modified by NetLogo/NetLogo#1380

### PR DESCRIPTION
**Pull request by Idloj**

### CODE REVIEW

**Comment by qiemem** [comment]
I'll merge this once NetLogo/NetLogo#1380 is merged.

**Comment by Idloj** [comment]
Sorry, opened it against the wrong branch. Now it can be merged (so I can update the ls on NetLogo/NetLogo#1380 to reference the warn-dialog-replace branch (on the main repo, not my fork))

**Comment by Idloj** [comment]
Travis fails because this is compiled against FileDialog that exists in NetLogo now. It should work after NetLogo/NetLogo#1380 is merged.

If there is a possibility to get out of this deadlock (travis fails here because NetLogo/NetLogo#1380 is not yet merged, and travis fails there because the submodules PRs aren't merged), *please* let me know.

**Comment by Idloj** [comment]
Please forgive my ignorance in using submodules

**Comment by mrerrormessage** [comment]
Merging in for now, this will only get merged to LS master once 1380 is merged.

**Pull request merged**
